### ISSUE TITLE
::jsfunctions help text does not agree with implementation

### ISSUE THREAD

**Issue by jclulow** [joyent/mdb_v8#18]
Looking at the output of "`::help jsfunctions`", it seems like the `-f` flag will allow filtering on the module filename:

```
> ::help jsfunctions

NAME
  jsfunctions - list JavaScript functions
...
OPTIONS

    -f file  List functions that were defined in a file whose name contains
             this substring.
...
```

In practice, it seems that the software is actually [expecting `-s`](https://github.com/joyent/mdb_v8/blob/f8dcc61167e852fd5110b885832f1fc349f07cf8/src/mdb_v8.c#L5327) for this purpose:

```
	if (mdb_getopts(argc, argv,
...
	    's', MDB_OPT_STR, &filename,
...
	    NULL) != argc)
		return (DCMD_USAGE);
```

**Comment by davepacheco** [comment]
Fixed in v0.11.1.
