### ISSUE TITLE
dict properties won't work with node v4.0 and v4.1

### ISSUE THREAD

**Issue by misterdjules** [joyent/mdb_v8#34]
https://codereview.chromium.org/1296743003/ landed in V8's master today and a PR to float it in node master and v4.x [was sent today as well](https://github.com/nodejs/node/pull/2959).

As a result, this metadata was not updated for node v4.0 and v4.1. Even if these releases are not considered LTS releases, I'm wondering if it's worth it to implement a workaround for this problem by hard-coding the type to `int` when V8's version is within the range of the versions used by node v4.0 and v4.1.

Hopefully https://github.com/nodejs/node/pull/2959 will land soon and will be available in the next v4.x releases.

**Comment by misterdjules** [comment]
https://github.com/nodejs/node/pull/2959 which updates `bit_field3`'s type and https://github.com/nodejs/node/pull/2974 which adds `ScopeInfo`'s constants to V8's post-mortem metadata have anded in nodejs/master, and are flagged to land in the next v4.x release.

So hopefully the post-mortem metadata for the next v4.x release of node will be more up to date.

**Comment by davepacheco** [comment]
Is this resolved by #32/#33?

**Comment by misterdjules** [comment]
Ah right, it's fixed by #33 with https://github.com/joyent/mdb_v8/pull/33/files#diff-38a6513060f0dadc2b8c2ea5c48a57d9R1067. Closing then.
