### ISSUE TITLE
clean up interfaces for working with functions and strings

### ISSUE THREAD

**Issue by davepacheco** [joyent/mdb_v8#35]
As part of the general internal interface clean-up, this ticket covers cleaning up the function-specific interfaces (like getting the name for a function, source code, instructions, and the like).

**Comment by davepacheco** [comment]
This ticket is a first step towards cleaning up various internal mdb_v8 interfaces.  There's a lot that could be done here, but I'm trying to focus on cleanup that's pretty clearly helpful in the short term.  (I actually started by developing crisper interfaces for new work, as with #17, and this is the first step that involves improving existing interfaces.)

I've polished a decent chunk of this in this branch:
https://github.com/joyent/mdb_v8/compare/joyent:master...davepacheco:dev-issue-35

The new interfaces are encapsulated in this file:
https://github.com/joyent/mdb_v8/blob/6b8cf0aa0b6f2bc4b10b6c63f5d766bcd239274b/src/mdb_v8_dbg.h

The interesting parts of this interface are implemented in these files:

https://github.com/joyent/mdb_v8/blob/6b8cf0aa0b6f2bc4b10b6c63f5d766bcd239274b/src/mdb_v8_string.c
https://github.com/joyent/mdb_v8/blob/6b8cf0aa0b6f2bc4b10b6c63f5d766bcd239274b/src/mdb_v8_subr.c
https://github.com/joyent/mdb_v8/blob/6b8cf0aa0b6f2bc4b10b6c63f5d766bcd239274b/src/mdb_v8_function.c

You'll find that there are some pretty strong conventions about how these interfaces look.  Because I want to do this incrementally rather than trying to rewrite mdb_v8, not everything has a new-style interface, nor have all the consumers been updated.  But several consumers have been updated, like dcmd_v8str() and dcmd_v8function().  The latter used to look like this:

https://github.com/joyent/mdb_v8/blob/2b2d9273fb6a636b634ce3102937f84406188182/src/mdb_v8.c#L3725-L3813

That code has direct knowledge of the structure of V8 functions -- knowledge that's duplicated in other dcmds like `jsframe`.  These commands do use some utility functions (like jsfunc_name() and jsfunc_lineno()), but even using these requires that the caller has already picked apart various V8 state.  The new function looks like this:

https://github.com/joyent/mdb_v8/blob/6b8cf0aa0b6f2bc4b10b6c63f5d766bcd239274b/src/mdb_v8.c#L3391-L3447

which I think is a lot cleaner.

CC @jclulow @misterdjules @rmustacc @bcantrill

**Comment by misterdjules** [comment]
It's a big diff and without having used these news interfaces myself, it's difficult to challenge them, but I can see clear improvements over what exists right now, and couldn't think of any red flag. I like where this is going.

**Comment by davepacheco** [comment]
Thanks for taking a look.

**Comment by davepacheco** [comment]
Last call for major feedback on this change.  (I'll still be happy to get feedback after this, but I'm going to land the change into master.)

**Comment by davepacheco** [comment]
It took me a long time to do enough regression-testing that I'm satisfied with the change, but I feel it's ready to integrate now.  On the plus side, my testing found several bugs that I fixed (mostly not regressions).  I'm pretty confident that this is a net step forward, but @misterdjules, please let me know if you want to take another look before I integrate it.

The delta from #master is here:
https://github.com/joyent/mdb_v8/compare/master...davepacheco:dev-issue-35

Here's the delta from the last review I sent out (on 10/8):
https://github.com/davepacheco/mdb_v8/compare/6b8cf0a...davepacheco:dev-issue-35
(This diff unfortunately includes two recent commits that are already in #master -- the "-g -O" change to GNUMakefile, and the "runtests_node" tool.)

The real work from the last time I sent this out includes:

- a new set of Developer's Notes (documentation)
- two new tools that I used to test: mdbv8diff and dumpjsobjects, both described in the new docs
- fixed an off-by-one bug I found in read_heap_dict() that caused us to report an erroneous extra property on some objects (in a non-deterministic way, to boot)
- fixed incorrect behavior from jsstr_print() when given garbage strings
- fixed a crash in dcmd_v8code() when given invalid values
- fixed a crash in v8function_free() when given a NULL pointer
- fixed the string truncation behavior to be more precise so that it was more appropriate to allocate a buffer of the appropriate size and then write a string into it.  (That still doesn't quite work when characters need to be escaped.)  This was surprisingly complicated, and still incomplete because of issue #49 (not a regression).
