### ISSUE TITLE
Improve documentation on how to find the appropriate function address (`addr`) when using `::jsclosure` 

### ISSUE THREAD

**Issue by misterdjules** [joyent/mdb_v8#54]
The [current documentation for `::jsclosure`](https://github.com/joyent/mdb_v8/blob/master/docs/usage.md#jsclosure) mentions:

```
Given a function identified by addr
```

but it's not clear what address `addr` is referring to, especially since by default `::jsstack` doesn't display the `JSFunction` instance's address.

Several users asked me for help on how to find the proper address to use with `::jsclosure`, which makes  me think that this aspect of `::jsclosure`'s documentation should be clearer and more explicit.

**Comment by davepacheco** [comment]
We used to print the JSFunction in ::jsstack, but I removed it from the default output because there was nothing useful you could do with it.  Now that you can do useful things with it, we should probably add it back.  That may help.

**Comment by misterdjules** [comment]
@davepacheco That seems reasonable to me. Does it make more sense for me to add that feature back in first, then if/when that change is merged, update https://github.com/joyent/mdb_v8/pull/55?

**Comment by misterdjules** [comment]
Closing that specific issue since it was about improving documentation and it's been done with e11c36ae427f1ded32790feb7c77e15d10d96d66, but I'll create another issue to make `::jsstack` print `JSFunction` instances by default.
