### ISSUE TITLE
Running `make` does not create a binary ?

### ISSUE THREAD

**Issue by matthiasg** [joyent/mdb_v8#64]
When cloning and running make I had expected an executable binary as output (mdb) but i only get a mdb_v8.so. What exactly do I have to do to get the mdb executable ? Is that a different project ?

Background: trying to debug an infinite loop here on node 5.5.0 on SmartOS 20151210T194528Z. Sadly running mdb directly does not seem to work .

**Comment by davepacheco** [comment]
This repository contains only an mdb module for V8.  mdb itself is part of illumos (and included in SmartOS).  You use this module by running mdb and then loading the module.

There's a tutorial and more documentation in the user guide:
https://github.com/joyent/mdb_v8/blob/master/docs/usage.md
