### ISSUE TITLE
Fix function name handling in V8 5.1.281.69

### ISSUE THREAD

**Issue by misterdjules** [joyent/mdb_v8#75]
As of https://github.com/nodejs/node/commit/2cc29517966de7257a2f1b34c58c77225a21e05d, node's master branch uses V8 at version 5.1.281.69.

That version comes with changes to how function names are handled: functions defined as part of variable declarations have their actual `name` property`set to the name of the variable.  Their`inferred_name` property is not set anymore, and has been removed.

So for instance, the following code:

```
var foo = function() {}
```

will create a `SharedFunctionInfo` object with its `name` property set to foo, and that `SharedFunctionInfo` object will not have an `inferred_name` property.

These change breaks the `tst.postmortem_jsstack.js` and `tst.postmortem_load.js` tests. They were implemented in V8 first behind a "harmony" flag with https://github.com/v8/v8/commit/2a20d5183795da933c1df46d95fc60692b123879, then "unstaged" and made available without using "harmony" flags with https://github.com/v8/v8/commit/c7eb436d09d5fa10ef41a3312edea2d7a2680126.

I'll submit a fix asap.

**Comment by stafyniaksacha** [comment]
Hello @misterdjules,

I have the same issue with the new LTS version of node which embed V8 at version 5.1.x

I've seen that you have begin a fix with your commit misterdjules/mdb_v8@79a93c474a3e7ba1d867ce03315be2a469a88d3a
Did you plan to release it ? Or, in case of not, can you explain what is missing ? 

Thanks you !

**Comment by misterdjules** [comment]
@stafyniaksacha https://github.com/misterdjules/mdb_v8/commit/79a93c474a3e7ba1d867ce03315be2a469a88d3a is not related to this issue. It implements the ability for mdb_v8 to find what closures reference a given object.

**Comment by misterdjules** [comment]
Closed as a duplicate of #77.
